---
PRODUCT_NAME: '$(TARGET_NAME)'
SWIFT_VERSION: '3.0'
COPY_PHASE_STRIP: 'NO'
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
ALWAYS_SEARCH_USER_PATHS: 'NO'
CLANG_ANALYZER_NONNULL: 'YES'
CLANG_CXX_LANGUAGE_STANDARD: gnu++0x
CLANG_CXX_LIBRARY: libc++
CLANG_ENABLE_MODULES: 'YES'
CLANG_ENABLE_OBJC_ARC: 'YES'
CLANG_WARN_BOOL_CONVERSION: 'YES'
CLANG_WARN_CONSTANT_CONVERSION: 'YES'
CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
CLANG_WARN_DOCUMENTATION_COMMENTS: 'YES'
CLANG_WARN_EMPTY_BODY: 'YES'
CLANG_WARN_ENUM_CONVERSION: 'YES'
CLANG_WARN_INFINITE_RECURSION: 'YES'
CLANG_WARN_INT_CONVERSION: 'YES'
CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
CLANG_WARN_SUSPICIOUS_MOVES: 'YES'
CLANG_WARN_UNREACHABLE_CODE: 'YES'
CLANG_WARN__DUPLICATE_METHOD_MATCH: 'YES'
GCC_WARN_64_TO_32_BIT_CONVERSION: 'YES'
GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
GCC_WARN_UNDECLARED_SELECTOR: 'YES'
GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
GCC_WARN_UNUSED_FUNCTION: 'YES'
GCC_WARN_UNUSED_VARIABLE: 'YES'
COPY_PHASE_STRIP: 'NO'
GCC_C_LANGUAGE_STANDARD: gnu99
GCC_NO_COMMON_BLOCKS: 'YES'
ENABLE_STRICT_OBJC_MSGSEND: 'YES'
