name: CI
on:
  push: {}
  pull_request: {}
jobs:
  run:
    runs-on: ${{ matrix.macos }}
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["15.3"]
        include:
          - xcode: "15.3"
            macos: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@master
      - name: Resolve
        run: swift package resolve
      - name: Build
        run: swift build
      - name: Test
        run: set -o pipefail && swift test 2>&1 | xcpretty
      - name: Gen fixtures
        run: scripts/gen-fixtures.sh
      - name: Check fixtures
        run: scripts/diff-fixtures.sh
      - name: Build fixtures
        run: scripts/build-fixtures.sh
  run-linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@master
      - name: Build and run tests
        run: swift test --enable-test-discovery
